from cudalog.utils import trycast
from dataclasses import dataclass

EVENTS = {
    10: "Disk Space Low",
    11: "Disk Space Critical",
    20: "Memory Low",
    21: "Memory Critical",
    30: "High System Load",
    31: "Excessive System Load",
    34: "Critical System Condition",
    35: "Power Outage",
    36: "Power Restored",
    48: "Device Mismatch",
    49: "Device Activation Failed",
    50: "Device Down",
    51: "IP Address Added",
    52: "IP Address Removed",
    53: "Duplicate IP Detected",
    54: "IP Property Change Failed",
    55: "Assigned IP Address Changed",
    56: "Duplicate DHCP IP",
    57: "Dyn DNS Update Succeeded",
    58: "Dyn DNS Update Failed",
    60: "Route Added",
    61: "Route Deleted",
    62: "Route Changed",
    63: "Route Enabled",
    64: "Route Disabled",
    65: "Route Reactivated",
    66: "Route Deactivated",
    70: "Flash Drive auto detection",
    80: "USB Device is not connected",
    90: "Module Error",
    100: "Missing Configuration File",
    110: "Missing Sysctrl",
    120: "Missing Executable",
    131: "Resource Missing",
    135: "Resource Limit Pending",
    136: "Resource Limit Exceeded",
    140: "Mail Size Limit Exceeded",
    150: "Corrupted Data File",
    300: "User ID (UID) Invalid",
    304: "Reserved Login ID Used",
    400: "Time Discontinuity Detected",
    500: "Invalid License",
    501: "No License Found",
    505: "License Limit Exceeded",
    510: "Invalid Argument",
    600: "HA Partner Unreachable",
    610: "Reporter SSH Host Key Mismatch",
    620: "Box Unreachable",
    622: "Box Reachable Again",
    666: "Process Core Found",
    700: "SIM Card Handling",
    701: "SIM Card Handling",
    702: "3G Network Registration",
    703: "3G Network Registration",
    704: "Signal Strength",
    710: "SMS Handling",
    711: "SMS Handling",
    721: "SMS Handling",
    2000: "Start Server",
    2001: "Start Service",
    2002: "Start Box Service",
    2010: "Stop Server",
    2011: "Stop Service",
    2012: "Stop Box Service",
    2020: "Restart Server",
    2021: "Restart Service",
    2022: "Restart Box Service",
    2030: "Block Server",
    2031: "Block Service",
    2032: "Block Box Service",
    2040: "Deactivate Server",
    2041: "Deactivate Service",
    2042: "Deactivate Box Service",
    2044: "No valid License for Service",
    2045: "Entering GRACE Mode",
    2046: "Entering DEMO Mode",
    2047: "GRACE Mode Expired",
    2050: "Reactivate Server",
    2051: "Reactivate Service",
    2052: "Reactivate Box Service",
    2054: "Subprocess Kill Requested",
    2056: "Connection Kill Requested",
    2058: "Session Kill Requested",
    2060: "Emergency Server Start",
    2061: "Emergency Server Stop",
    2070: "Daemon Startup Failed",
    2071: "Daemon Startup Succeeded",
    2072: "Daemon Shutdown Failed",
    2073: "Daemon Shutdown Succeeded",
    2080: "Time Synchronisation Failed",
    2081: "Time Synchronisation Succeeded",
    2082: "Time Synchronisation Denied",
    2099: "CTRL-ALT-DEL",
    2100: "Reboot Requested",
    2101: "System Halt Requested",
    2102: "Network Restart Requested",
    2103: "Activate New Network Configuration",
    2104: "Firewall Start",
    2105: "Firewall Stop",
    2120: "Mail DSN Message Sent",
    2210: "Network Subsystem Restart",
    2212: "Unclean Network Subsystem Activation",
    2220: "Network Subsystem Shutdown",
    2222: "Unclean Network Subsystem Shutdown",
    2230: "Network Subsystem Check",
    2232: "Network Subsystem Check",
    2234: "Network Subsystem Check Failed",
    2240: "Link Activation Failed",
    2242: "Sublink Activation Failed",
    2250: "PCMCIA Bus Reset",
    2380: "Flawed Configuration Data Activation",
    2400: "Config Node Change Notice",
    2401: "Config Node Change Warning",
    2402: "Config Node Change Alert",
    2420: "Login Notice",
    2421: "Login Warning",
    2422: "Login Alert",
    2500: "FW Forwarding Loop Suppressed",
    2502: "FW Local Redirection Suppressed",
    2510: "FW Global Connection Limit Exceeded",
    2511: "FW Worker Limit Exceeded",
    2600: "DHCP Lease Deleted",
    3000: "VPN Service Tunnel Terminated",
    3001: "VPN Alternative Tunnel Activated",
    3002: "VPN Service Tunnel Activated",
    3003: "VPN Service On Demand Tunnel Activated",
    3004: "VPN Service On Demand Tunnel Deactivated",
    3005: "Network Access Client Connected",
    3006: "Network Access Client Disconnected",
    3011: "CRL Collection Failed",
    3012: "Network Access Client Version",
    3013: "Virus Scanner Update Failed",
    4000: "FW Port Scan Detected",
    4002: "FW Flood Ping Protection Activated",
    4004: "FW Activating Perimeter Defence (inbound mode)",
    4006: "FW Pending TCP Connection Limit Reached",
    4008: "FW UDP Connection per Source Limit Exceeded",
    4009: "FW UDP Connection Limit Exceeded",
    4010: "FW Oversized SYN Packet Dumped",
    4012: "FW Large ICMP Packet Dumped",
    4014: "FW IP Spoofing Attempt Detected",
    4015: "FW Potential IP Spoofing Attempt",
    4016: "FW Rule Connection Limit Exceeded",
    4018: "FW Rule Connection per Source Limit Exceeded",
    4020: "FW Rule Notice",
    4021: "FW Rule Warning",
    4022: "FW Rule Alert",
    4023: "FW Rule Idle Alert",
    4024: "FW Global Connection per Source Limit Exceeded",
    4026: "FW ICMP-ECHO Connection per Source Limit Exceeded",
    4027: "FW ICMP-ECHO Connection Limit Exceeded",
    4028: "FW OTHER-IP Connection per Source Limit Exceeded",
    4029: "FW OTHER-IP Session Limit Exceeded",
    4050: "FW ARP MAC Address Changed",
    4051: "FW ARP Ambiguous Duplicate Reply",
    4052: "FW ARP Request Device Mismatch",
    4053: "FW ARP Reverse Routing Interface Mismatch",
    4054: "FW RSTP Interface Role Changed",
    4055: "FW Access Ruleset Installation Failure",
    4056: "FW Application Ruleset Installation Failure",
    4060: "IPS Log Notice",
    4061: "IPS Log Warning",
    4062: "IPS Log Alert",
    4063: "IPS Drop Notice",
    4064: "IPS Drop Warning",
    4065: "IPS Drop Alert",
    4100: "User Unknown",
    4110: "Authentication Failure Notice",
    4111: "Authentication Failure Warning",
    4112: "Authentication Failure Alert",
    4113: "DC Agent communication failure",
    4118: "Session Authorization Request",
    4120: "Session Opened Notice",
    4121: "Session Opened Warning",
    4122: "Session Opened Alert",
    4124: "Remote Command Execution Notice",
    4125: "Remote Command Execution Warning",
    4126: "Remote Command Execution Alert",
    4130: "System Login Notice",
    4131: "System Login Warning",
    4132: "System Login Alert",
    4160: "Log Data Deleted",
    4162: "Statistics Data Deleted",
    4163: "Statistics Data Collection Failed",
    4200: "CTRL-ALT-DEL",
    4202: "System Reboot",
    4204: "System Shutdown",
    4206: "Runlevel Changed",
    4210: "Single User Mode",
    4212: "Problems During Bootup",
    4214: "Incomplete Previous Boot",
    4220: "System Boot",
    4222: "Emergency System Boot",
    4240: "Bootloader Configuration Change",
    4242: "Two Phase Kernel Update",
    4244: "Automatic Kernel Update",
    4246: "Kernel Update Rejected",
    4248: "Custom Bootloader or Kernel Update",
    4250: "Bootloader Test  Activation Failure",
    4252: "Bootloader Activation Failed",
    4254: "Bootloader Disaster Recovery",
    4256: "Bootloader Reconfigured",
    4258: "Kernel Update",
    4260: "Pending Kernel Update",
    4261: "Activate Pending Kernel Update",
    4262: "Bootloader Reconfiguration Failed",
    4264: "Kernel Update Failed",
    4300: "Empty ACL Encountered",
    4302: "Overlong ACL Encountered",
    4304: "Password or Key Update Failure",
    4306: "Password Updated",
    4307: "Key Updated",
    4320: "Emergency Override triggered",
    4400: "Firmware Update Triggered",
    4402: "Subsystem Release Update Succeeded",
    4404: "Subsystem Release Update Cancelled",
    4406: "Subsystem Release Update Aborted",
    4408: "Firmware Update Failed",
    4410: "Release Inconsistencies Detected",
    4412: "Active Kernel not in RPM-DB",
    4450: "New Software Update",
    4460: "New Product Tip",
    4500: "Mail Data Discarded",
    4504: "Mail Operation Changed",
    4506: "Mail Delivery Refused",
    4508: "Mail Relaying Denied",
    4512: "Mail Rule Notice",
    4513: "Mail Rule Warning",
    4514: "Mail Rule Alert",
    4600: "Attempted Illegal Assignment",
    4700: "Query Activation State Failed",
    4701: "Got Unknown Activation State",
    4702: "License Download Failed",
    4800: "File or Pattern Update Failed",
    5000: "User added to ATP quarantine",
    5001: "ATP malicious activity detected",
    5002: "ATP Cloud status",
    5003: "ATP Cloud status",
    5004: "DNS Sinkhole address accessed",
    5005: "Virus Scanner Blocked File",
}
LONGEST = len(EVENTS[max(EVENTS, key=lambda k: len(EVENTS[k]))])


@dataclass
class Event:
    id: int
    name: str

    @staticmethod
    def from_id(id: int | str) -> "Event":
        id = trycast(int, id, 0)
        name = EVENTS.get(id, "Unknown")
        return Event(id, name)
